<a href="https://colab.research.google.com/github/Kamalakannan-1208/Python-Programming-Fundamentals/blob/main/Day_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

stacking

In [ ]:
import numpy as np
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7,8,9],[10,11,12]])
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(2, 3)


In [ ]:
# stack
array3=np.stack((array1,array2),axis=0)
print(array3)
print(array3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
# axis 1
array4=np.stack((array1,array2),axis=1)
print(array4)
print(array4.shape)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
# axis 2
array5=np.stack((array1,array2),axis=2)
print(array5)
print(array5.shape)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
(2, 3, 2)


In [ ]:
# vstack
print(np.vstack((array1,array2)))
print(np.vstack((array1,array2)).shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [ ]:
# hstack
print(np.hstack((array1,array2)))
print(np.hstack((array1,array2)).shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


In [ ]:
# row wise
print(np.row_stack((array1,array2)))
print(np.row_stack((array1,array2)).shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


/tmp/ipython-input-11-1686365091.py:2: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((array1,array2)))
/tmp/ipython-input-11-1686365091.py:3: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((array1,array2)).shape)


In [ ]:
# column wise
print(np.column_stack((array1,array2)))
print(np.column_stack((array1,array2)).shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


In [ ]:
# dstack
print(np.dstack((array1,array2)))
print(np.dstack((array1,array2)).shape)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
(2, 3, 2)


splitting


In [ ]:
# must be equal split
import numpy as np
arrays=np.array([1,2,3,4,5,6])
ans=np.split(arrays,3)
print(ans)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# unequal split
print(np.array_split(arrays,4))

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
# hsplit 1 d and more

In [ ]:
arrayspl=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print(np.hsplit(arrays,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# vertical 2d and more
print(np.vsplit(arrayspl,3))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
# depth
threed=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(np.dsplit(threed,3))

[array([[[ 1],
        [ 4]],

       [[ 7],
        [10]]]), array([[[ 2],
        [ 5]],

       [[ 8],
        [11]]]), array([[[ 3],
        [ 6]],

       [[ 9],
        [12]]])]
