<a href="https://colab.research.google.com/github/Kamalakannan-1208/Python-Programming-Fundamentals/blob/main/Day_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INDEXING

In [1]:
import numpy
array=numpy.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],dtype='int16')
print(array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [2]:
array[1]

array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int16)

In [3]:
# slicing
# row
array[1,:]

array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int16)

In [4]:
array[1,1]

array([10, 11, 12], dtype=int16)

In [5]:
array[1,1,1]

np.int16(11)

In [6]:
#Modifying
array[1,1]=[1,2,3]
print(array)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [7]:
# boolean indexing
array[array>5]

array([6, 7, 8, 9], dtype=int16)

In [8]:
# ellipsis
array1=numpy.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(array1[0,::])
print(array1[0,...])

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [9]:
#new axis col 2d to 3d
print(array1[:,numpy.newaxis])
print("----------")
print(array1[numpy.newaxis,:])

[[[ 1  2  3  4  5  6  7]]

 [[ 8  9 10 11 12 13 14]]]
----------
[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]]


PROBLEM STATEMENT

In [10]:
import numpy as np
pb_array=np.ones((5,5),dtype="int32")
print(pb_array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
pb1_array=np.zeros((3,3),dtype="int32")
pb1_array[1,1]=9
print(pb1_array)

[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [12]:
pb_array[1:4,1:4]=pb1_array
print(pb_array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [13]:
# reshape
array2=np.array([[1,2,3,4],[5,6,7,8]])
print(array2.reshape(8))
print(array2)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [14]:
# resize
array2.resize(4,2)
print(array2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
#flattening array
flaten=array2.ravel()
flaten

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
# faltten array
flat=array2.flatten()
flat

array([1, 2, 3, 4, 5, 6, 7, 8])