<a href="https://colab.research.google.com/github/Kamalakannan-1208/Python-Programming-Fundamentals/blob/main/Day_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Arithmetic operations

In [19]:
# addition
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,np.nan])
print(np.add(arr1,arr2))

[ 5.  7. nan]


In [20]:
# subraction
print(np.subtract(arr1,arr2))

[-3. -3. nan]


In [21]:
# multiplication
arr3=[6,7,8]
print(np.multiply(arr1,arr3))

[ 6 14 24]


In [22]:
# division
print(np.divide(arr1,arr3))

[0.16666667 0.28571429 0.375     ]


In [23]:
#mod
print(np.mod(arr1,2))

[1 0 1]


In [24]:
#exp
print(arr1)
np.power(arr1,2,out=arr1)
print(arr1)


[1 2 3]
[1 4 9]


Aggregation operation

In [33]:
print(np.max(arr1))

9


In [36]:
print(np.min(arr1))

1


In [34]:
#minimum
print(np.minimum(arr1,arr2))

[ 1.  4. nan]


In [28]:
#maxmum
print(np.maximum(arr1,arr2))


[ 4.  5. nan]


In [29]:
#sum
print(np.sum(arr1))

14


In [30]:
#mean
print(np.mean(arr1))

4.666666666666667
