<a href="https://colab.research.google.com/github/Kamalakannan-1208/Python-Programming-Fundamentals/blob/main/Day_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aggregation Function

In [1]:
import numpy
arr=[1,2,3,4,5]
# median
print(numpy.median(arr))

# std
print(numpy.std(arr))


3.0
1.4142135623730951


In [ ]:
# variance
print(numpy.var(arr))

Linear Algebra

In [7]:
## matrix manipulation

matrix1=numpy.array([[1,2],[4,5]])
matrix2=numpy.array([[7,8],[9,10]])

# addition
print("addition\n",numpy.add(matrix1,matrix2))

# subraction
print("subtraction\n",numpy.subtract(matrix1,matrix2))

# multiplication
print("multiplication\n",numpy.multiply(matrix1,matrix2))

# division
print("division\n",numpy.divide(matrix1,matrix2))

#dot
print("dot\n",numpy.dot(matrix1,matrix2))


#squart
print("squart\n",numpy.sqrt(matrix1))

# sum
print("sum\n",numpy.sum(matrix1))

addition
 [[ 8 10]
 [13 15]]
subtraction
 [[-6 -6]
 [-5 -5]]
multiplication
 [[ 7 16]
 [36 50]]
division
 [[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
dot
 [[25 28]
 [73 82]]
squart
 [[1.         1.41421356]
 [2.         2.23606798]]
sum
 12


In [8]:
## product of vetor and matrices

# inner
print("inner\n",numpy.inner(matrix1,matrix2))

# cross
print("cross\n",numpy.cross(matrix1,matrix2))

#outer
print("outer\n",numpy.outer(matrix1,matrix2))

inner
 [[23 29]
 [68 86]]
cross
 [-6 -5]
outer
 [[ 7  8  9 10]
 [14 16 18 20]
 [28 32 36 40]
 [35 40 45 50]]


/tmp/ipython-input-8-912217406.py:7: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print("cross\n",numpy.cross(matrix1,matrix2))


In [11]:
#determinant
print("determinant\n",numpy.linalg.det(matrix1))

#inverse
print("inverse\n",numpy.linalg.inv(matrix1))

#rank
print("rank\n",numpy.linalg.matrix_rank(matrix1))

determinant
 -2.9999999999999996
inverse
 [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
rank
 2
