<a href="https://colab.research.google.com/github/Kamalakannan-1208/Python-Programming-Fundamentals/blob/main/Day_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPy

In [33]:
import numpy as np
# array creation 1d
array=np.array([1,2,3])
print(array)

[1 2 3]


In [34]:
# attributes of array
print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)
print(array.itemsize)
print(array.nbytes)

1
(3,)
3
int64
8
24


In [35]:
# 2d array
array2=np.array([[1,2,3],[4,5,6]])
print(array2)
# 3d array
array3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array3)

[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [36]:
print(array2.ndim, array3.ndim)

2 3


Methods to create array

In [37]:
#zeros method
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [38]:
#ones method
ones=np.ones((2,3,4),dtype='int16')
print(ones)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [39]:
# full method
full=np.full((2,3),4)
print(full)

[[4 4 4]
 [4 4 4]]


In [40]:
# arrange method
arrange=np.arange(10,20,2)
print(arrange)

[10 12 14 16 18]


In [41]:
#linespace
linespace=np.linspace(0,1,num=5)
print(linespace)

[0.   0.25 0.5  0.75 1.  ]


In [42]:
#random 0 to 1 range
random_array=np.random.rand(2,3)
print(random_array)

[[0.76176525 0.63969034 0.83692563]
 [0.41337887 0.91753025 0.77135981]]


In [43]:
# random with given range
random_array_nd=np.random.randn(2,3)
print(random_array_nd)

[[-1.64640061 -0.59436562  0.292687  ]
 [-0.08537021  0.07376843  0.78033863]]


In [44]:
# random element in array in integer
ramdom_integer=np.random.randint(0,10,size=(2,3))
print(ramdom_integer)

[[3 8 8]
 [5 7 8]]


In [45]:
# full_like method
full_like=np.full_like(ones,5)
print(full_like)

[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [46]:
# zeros_like method
zeros_like=np.zeros_like(ones)
print(zeros_like)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [47]:
# ones_like method
ones_like=np.ones_like(zeros_like)
print(ones_like)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [48]:
# identity matrix support operation
identity=np.eye(2,3,k=1)
print(identity)

[[0. 1. 0.]
 [0. 0. 1.]]


In [49]:
# acquarate identity matrix
identity_like=np.identity(2)
print(identity_like)

[[1. 0.]
 [0. 1.]]


In [50]:
# diagonal matrix
diag=np.diag(identity_like)
print(diag)

[1. 1.]
